<?php

/**
 * @file
 * Contains commerce_securepayau.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function commerce_securepayau_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_securepayau module.
    case 'help.page.commerce_securepayau':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SecurePay') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_securepayau_form_commerce_payment_gateway_add_form_alter(&$form, FormStateInterface $form_state) {
  $moduleHandler = \Drupal::service('module_handler');
  if (!$moduleHandler->moduleExists('oauth2_client')) {
    unset($form['plugin']['#options']['securepayau_paypal_express_checkout']);
  }
}
