commerce_payment.commerce_payment_gateway.plugin.secure_pay:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    password:
      type: string
      label: 'Password'
